springops:
    azure-spring-cloud:
        resource-group: rg-springcloudlab
        service-name: asclabfmiguel
        subscription-id: 98bc5d13-2aa1-45cb-bf49-45aa47e220bf
    git:
        uri: https://github.com/felipmiguel/asc-workshop.git
        user: 
        password:  
        baseDirectory: /home/fmiguel/springops